camera:
  position:
    x: 0
    y: 0
    z: -5
  focus_point:
    x: 0
    y: 0
    z: -5.1
  size:
    width: 5
    height: 5
  direction:
    x: 0
    y: 0
    z: 1
  output:
    size:
      width: 500
      height: 500
    file: out.png
  misc:
    max_ray_depth: 10
    exposure: 1000000
lights:
  count: 1
  lights:
    0:
      position:
        x: 0
        y: 0
        z: -1
      brightness: 0.001
object:
  name: wall
  position:
    x: 0
    y: 0
    z: 0
# END