camera:
  position:
    x: 0
    y: 0
    z: -10
  focus_point:
    x: 0
    y: 0
    z: -11
  size:
    width: 1
    height: 1
  direction:
    x: 0
    y: 0
    z: 1
  output:
    size:
      width: 800
      height: 800
    file: out.png
  misc:
    max_ray_depth: 10
    exposure: 10000000
lights:
  count: 1
  lights:
    0:
      position:
        x: 0
        y: 3
        z: -3
      brightness: 0.001
object:
  name: cube
  position:
    x: 0
    y: 0
    z: 0
# END