camera:
  position:
    x: 0
    y: 0
    z: -10
  size:
    width: 1
    height: 1
  direction:
    x: 0
    y: 0
    z: 1
  output:
    size:
      width: 50
      height: 50
    file: out.png
  misc:
    max_ray_depth: 10
    exposure: 1000000
lights:
  count: 2
  lights:
    0:
      position:
        x: 0
        y: 3
        z: -3
      brightness: 0.001
    1:
      position:
        x: 0
        y: -3
        z: 3
      brightness: 0.001
object:
  name: cube
  position:
    x: 0
    y: 0
    z: 0
# END